---
- name: "Install Node.js 13"
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
    sudo apt-get install -y nodejs

    sudo npm install -g n
    sudo n 13.8.0

- name: "Install PM2 Globally"
  npm:
    name: pm2
    global: yes
# ---
# - name: "add nodejs 13"
#   become: true
#   shell: |
#      curl -fsSL https://deb.nodesource.com/setup_13.x | bash -
#      apt-get install -y nodejs
     
# - name: "install pm2 globally"
#   become: true
#   npm:
#     name: pm2
#     global: yes
