---
- name: "add nodejs 13"
  become: true
  shell: |
     curl -fsSL https://deb.nodesource.com/setup_13.x | bash -
     apt-get install -y nodejs
     
- name: "install pm2 globally"
  become: true
  npm:
    name: pm2
    global: yes
# - name: "install node 13.X"
#   shell: |
#       # Install Node.js LTS version as our base Node.js version
#       curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
#       sudo apt install -y nodejs

#       # Use n version manager to use Node.js v13.8.0
#       sudo npm install -global n
#       sudo n 13.8.0

# - name: "install pm2 globally"
#   become: true
#   npm:
#     name: pm2
#     global: yes