# - name: "Add Node.js from Nodesource"
#   shell: |
#     curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
#    sudo apt -y upgrade
#    sudo apt install -y nodejs

- name: "install node 13.X"
  shell: |
      # Install Node.js LTS version as our base Node.js version
      curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
      sudo apt-get install -y nodejs

      # Use n version manager to use Node.js v13.8.0
      sudo npm install -g n
      sudo n 13.8.0

- name: "install pm2 globally"
  become: true
  npm:
    name: pm2
    global: yes
    # production: yes
    # state: present

# - name: "copy files from CircleCI to server"
#   copy:
#     src: /root/project/backend
#     dest: /home/ubuntu

# - name: "install package dependencies"
#   shell: |
#     cd /home/ubuntu/backend    
#     npm install 